version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '14:30'
      timezone: Europe/Zurich
    groups:
       github-actions:
          patterns: ['*']
