env:
  browser: true
  jquery: true
  es6: true

plugins:
  - react-hooks
  - prettier

extends:
  - 'indico'
  - 'indico/babel'
  - 'indico/react'
  - 'indico/react-hooks'
  - 'indico/prettier'
  - 'prettier/babel'
  - 'prettier/react'

settings:
  # we don't use the webpack resolver because it is SLOW (~1s),
  # but our custom resolver does the job just fine while still
  # being fast.
  import/resolver:
    alias:
      map:
        - ['indico/modules/core', './indico/modules/core/client/js']
        - ['indico/modules/rb', './indico/modules/rb/client/js']
        - ['indico/modules/users', './indico/modules/users/client/js']
        - ['indico', './indico/web/client/js']
      extensions: [.js, .jsx, .json]
  react:
    version: detect

rules:
  import/no-unresolved:
    - error
    - ignore: ['^indico-url:']
  new-cap:
    - error
    - capIsNewExceptionPattern: '\$\.(Event|Deferred)$'
  prefer-template: warn

globals:
  Indico: false
  IndicoUI: false
  global: false
  require: false
  process: false
