env:
  browser: true
  jquery: true
  es6: true
  jest/globals: true

plugins:
  - react-hooks
  - prettier
  - jest
  - '@typescript-eslint'

extends:
  - 'indico'
  - 'indico/babel'
  - 'indico/react'
  - 'indico/react-hooks'
  - 'indico/prettier'

settings:
  # we don't use the webpack resolver because it is SLOW (~1s),
  # but our custom resolver does the job just fine while still
  # being fast.
  import/resolver:
    alias:
      map:
        - ['indico/modules/core', './indico/modules/core/client/js']
        - ['indico/modules/dev', './indico/modules/dev/client/js']
        - ['indico/modules/rb', './indico/modules/rb/client/js']
        - ['indico/modules/users', './indico/modules/users/client/js']
        - ['indico/modules/search', './indico/modules/search/client/js']
        - ['indico/modules/events/reviewing', './indico/modules/events/client/js/reviewing']
        - ['indico/modules/events/editing', './indico/modules/events/editing/client/js']
        - ['indico/modules/events/management', './indico/modules/events/management/client/js']
        - ['indico/modules/events/persons', './indico/modules/events/persons/client/js']
        - ['indico/modules/events/timetable', './indico/modules/events/timetable/client/js']
        - ['indico/modules/events', './indico/modules/events/client/js']
        - ['indico', './indico/web/client/js']
        - ['axios/unsafe', './node_modules/axios/lib']
      extensions: [.js, .jsx, .json, .ts, .tsx]
  import/internal-regex: ^indico/
  react:
    version: detect

rules:
  curly:
    - error
    - all
  import/no-unresolved:
    - error
    - ignore: ['^indico-url:']
  import/no-cycle:
    - warn
  import/order:
    - error
    - groups: [builtin, external, internal, parent, sibling, index]
      alphabetize:
        order: asc
        caseInsensitive: true
      pathGroups:
        - pattern: indico-url:*
          group: external
          position: before
        - pattern: '{.,..,../..,../../..}/**/*.+(css|scss)' # eslint-plugin-import#1239
          group: sibling
          position: after
      pathGroupsExcludedImportTypes: [builtin]
      newlines-between: always
  new-cap:
    - error
    - capIsNewExceptionPattern: '\$\.(Event|Deferred|Color)$'
  prefer-template: warn
  react/no-unknown-property:
    - error
    - ignore: [styleName]
  no-restricted-globals:
    - error
    - event
  react/require-default-props: off

overrides:
  - files:
      - indico/web/client/js/react/components/**/*
      - indico/web/client/js/react/forms/final-form.jsx
      - indico/modules/rb/**/*
    rules:
      import/no-cycle: off
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: './tsconfig.json'
    extends:
      - 'plugin:@typescript-eslint/strict'
      - 'plugin:@typescript-eslint/stylistic'
      - 'plugin:import/typescript'
    rules:
      # https://stackoverflow.com/questions/63961803/eslint-says-all-enums-in-typescript-app-are-already-declared-in-the-upper-scope
      no-shadow: off
      '@typescript-eslint/no-shadow': 'warn'
  - files: ["*.d.ts"]
    rules:
      import/unambiguous: off
      '@typescript-eslint/no-unused-vars' : off
  - files: ["*.ts"]
    rules:
      'lines-between-class-members': off

globals:
  Indico: false
  IndicoUI: false
  global: false
  require: false
  process: false
