env:
  browser: true
  jquery: true
  es6: true
  jest/globals: true

plugins:
  - react-hooks
  - prettier
  - jest

extends:
  - 'indico'
  - 'indico/babel'
  - 'indico/react'
  - 'indico/react-hooks'
  - 'indico/prettier'
  - 'prettier/babel'
  - 'prettier/react'

settings:
  # we don't use the webpack resolver because it is SLOW (~1s),
  # but our custom resolver does the job just fine while still
  # being fast.
  import/resolver:
    alias:
      map:
        - ['indico/modules/core', './indico/modules/core/client/js']
        - ['indico/modules/rb', './indico/modules/rb/client/js']
        - ['indico/modules/users', './indico/modules/users/client/js']
        - ['indico/modules/search', './indico/modules/search/client/js']
        - ['indico/modules/events/reviewing', './indico/modules/events/client/js/reviewing']
        - ['indico/modules/events/editing', './indico/modules/events/editing/client/js']
        - ['indico/modules/events', './indico/modules/events/client/js']
        - ['indico', './indico/web/client/js']
      extensions: [.js, .jsx, .json]
  import/internal-regex: ^indico/
  react:
    version: detect

rules:
  curly:
    - error
    - all
  import/no-unresolved:
    - error
    - ignore: ['^indico-url:']
  import/no-cycle:
    - warn
  import/order:
    - error
    - groups: [builtin, external, internal, parent, sibling, index]
      alphabetize:
        order: asc
        caseInsensitive: true
      pathGroups:
        - pattern: indico-url:*
          group: external
          position: before
        - pattern: '{.,..,../..,../../..}/**/*.+(css|scss)' # eslint-plugin-import#1239
          group: sibling
          position: after
      pathGroupsExcludedImportTypes: [builtin]
      newlines-between: always
  new-cap:
    - error
    - capIsNewExceptionPattern: '\$\.(Event|Deferred)$'
  prefer-template: warn
  react/jsx-curly-brace-presence:
    # remove this override once they fixed this rule (probably in the next update)
    # check e.g. with indico/modules/rb/client/js/components/TimeInformation.jsx
    # where it should NOT remove the `{', '}` since it's required for proper spacing
    - error
    - children: ignore
  no-restricted-globals:
    - error
    - event

globals:
  Indico: false
  IndicoUI: false
  global: false
  require: false
  process: false
