root: true
owner: CERN
start_year: 2002
substring: This file is part of
template: |-
  {comment_start} This file is part of Indico.
  {comment_middle} Copyright (C) {dates} {owner}
  {comment_middle}
  {comment_middle} Indico is free software; you can redistribute it and/or
  {comment_middle} modify it under the terms of the MIT License; see the
  {comment_middle} LICENSE file for more details.
  {comment_end}
