printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: consistent
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: false
jsxBracketSameLine: false
arrowParens: avoid
endOfLine: lf
