version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
    nodejs: '20'
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv $READTHEDOCS_VIRTUALENV_PATH
    # RTD python versions are usually behind a bit...
    - sed -i -E "/^requires-python = /d" pyproject.toml
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install -r docs/requirements.txt
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install -e .[dev]
    - npm install -g @mermaid-js/mermaid-cli
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m sphinx -T -b dirhtml -d docs/_build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html
