version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "19"
  jobs:
    post_install:
      - npm install -g @mermaid-js/mermaid-cli

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
