options:
  merge-default-rules: false

files:
  include: 'indico/htdocs/sass/**/*.scss'
  ignore: 'indico/htdocs/sass/lib/**/*'

rules:
  attribute-quotes: 1
  bem-depth: 0
  border-zero:
    - 1
    - convention: none
  brace-style:
    - 2
    - style: 1tbs
      allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
      allow-leading-underscore: false
  clean-import-paths: 2
  declarations-before-nesting: 1
  empty-args:
    - 1
    - include: true
  empty-line-between-blocks: 1
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
      allow-leading-underscore: true
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
      allow-leading-underscore: false
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  max-file-line-count:
    - 1
    - length: 750
  max-line-length:
    - 2
    - length: 120
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
      allow-leading-underscore: true
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 4
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties:
    - 1
    - exclude: [background-image]
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 0
  no-warn: 1
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
      allow-leading-underscore: false
  property-sort-order: 0
  property-units: 0
  pseudo-element: 1
  quotes:
    - 1
    - style: single
  shorthand-values:
    - 1
    - allowed-shorthands: [1, 2]
  single-line-per-selector: 0
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 0
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
      allow-leading-underscore: false
  zero-unit: 2
