#!/usr/bin/env python

'''This script runs a single test file given as an argument'''
import os
import shutil
import sys
import unittest
import tempfile

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print '''
    Usage: %s <testFile.py>
''' % sys.argv[0]
        sys.exit()
        
    testName = sys.argv[1].replace(".py", "").replace('/', '.')
    sys.path = [os.path.join(os.path.dirname(__file__), '..', 'indico'), os.path.join(os.path.dirname(__file__), '..')] + sys.path
    mod = __import__(testName)
    unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromModule(sys.modules[testName]))
