include(ScriptRoot + "indico/Management/RoomBooking.js");
include(ScriptRoot + "indico/Management/ConfModifDisplay.js");
include(ScriptRoot + "indico/Management/Users.js");
include(ScriptRoot + "indico/Management/eventCreation.js");
include(ScriptRoot + "indico/Management/Timetable.js");
include(ScriptRoot + "indico/Management/RoomBookingMapOfRooms.js");
include(ScriptRoot + "indico/Management/NotificationTPL.js");
include(ScriptRoot + "indico/Management/AbstractReviewing.js");
include(ScriptRoot + "indico/Management/CFA.js");
