"""Add include_description to reminders

Revision ID: 40d4569835b8
Revises: 
Create Date: 2017-11-17 10:35:12.378432
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '40d4569835b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('include_description', sa.Boolean(), nullable=False, default=False,
	 server_default='false'), schema='events')
    op.alter_column('reminders', sa.Column('include_description', sa.Boolean(), nullable=False, default=False),
	 schema='events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'include_description', schema='events')
    # ### end Alembic commands ###
