"""Add semantic field names

Revision ID: 5f0186422ed0
Revises: 566d5de4e0e5
Create Date: 2017-11-27 13:12:31.539582
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '5f0186422ed0'
down_revision = '566d5de4e0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
              sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_names')),
              schema='event_registration')
    op.create_index(op.f('ix_uq_semantic_names_name'), 'semantic_names', ['name'], unique=True,
                    schema='event_registration')
    op.add_column('form_items', sa.Column('semantic_name_id', sa.Integer(), nullable=True),
                  schema='event_registration')
    op.create_foreign_key(op.f('fk_form_items_semantic_name_id_semantic_names'), 'form_items',
                          'semantic_names', ['semantic_name_id'], ['id'],
                          source_schema='event_registration', referent_schema='event_registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_form_items_semantic_name_id_semantic_names'), 'form_items',
                       schema='event_registration', type_='foreignkey')
    op.drop_column('form_items', 'semantic_name_id', schema='event_registration')
    op.drop_index(op.f('ix_uq_semantic_names_name'), table_name='semantic_names',
                  schema='event_registration')
    op.drop_table('semantic_names', schema='event_registration')
    # ### end Alembic commands ###
