"""Add fields for speaker profile

Revision ID: 73e4211e743e
Revises: 932389d22b1f
Create Date: 2026-01-27 14:44:58.257055
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '73e4211e743e'
down_revision = '932389d22b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('speaker_photo_file_id', sa.Integer(), nullable=True), schema='events')
    op.add_column('persons', sa.Column('speaker_description', sa.Text(), nullable=True), schema='events')
    op.create_foreign_key(op.f('fk_persons_speaker_photo_file_id_files'), 'persons', 'files', ['speaker_photo_file_id'], ['id'], source_schema='events', referent_schema='indico')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_persons_speaker_photo_file_id_files'), 'persons', schema='events', type_='foreignkey')
    op.drop_column('persons', 'speaker_description', schema='events')
    op.drop_column('persons', 'speaker_photo_file_id', schema='events')
    # ### end Alembic commands ###
