"""Add speaker profile-related fields

Revision ID: 0564ff0a9dc3
Revises: e1e229910f7e
Create Date: 2026-02-19 10:57:25.655927
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '0564ff0a9dc3'
down_revision = 'e1e229910f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('speaker_photo_file_id', sa.Integer(), nullable=True), schema='events')
    op.add_column('persons', sa.Column('speaker_description', sa.Text(), nullable=True), schema='events')
    op.add_column('persons', sa.Column('speaker_linkedin', sa.Text(), nullable=True), schema='events')
    op.add_column('persons', sa.Column('speaker_facebook', sa.Text(), nullable=True), schema='events')
    op.add_column('persons', sa.Column('speaker_github', sa.Text(), nullable=True), schema='events')
    op.add_column('persons', sa.Column('speaker_webpage', sa.Text(), nullable=True), schema='events')
    op.create_foreign_key(op.f('fk_persons_speaker_photo_file_id_files'), 'persons', 'files', ['speaker_photo_file_id'], ['id'], source_schema='events', referent_schema='indico')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_persons_speaker_photo_file_id_files'), 'persons', schema='events', type_='foreignkey')
    op.drop_column('persons', 'speaker_description', schema='events')
    op.drop_column('persons', 'speaker_photo_file_id', schema='events')
    op.drop_column('persons', 'speaker_github', schema='events')
    op.drop_column('persons', 'speaker_facebook', schema='events')
    op.drop_column('persons', 'speaker_linkedin', schema='events')
    op.drop_column('persons', 'speaker_webpage', schema='events')
    # ### end Alembic commands ###
